/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Cash = IDL.Nat;
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'cash' : IDL.Nat,
});
export const PlayerID = IDL.Principal;
export const Time = IDL.Int;
export const Speed = IDL.Nat;
export const Player = IDL.Record({
  'id' : PlayerID,
  'cash' : Cash,
  'joinedAt' : Time,
  'hasClaimedReward' : IDL.Bool,
  'clickSpeed' : Speed,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCash' : IDL.Func([], [], []),
  'adminAddCash' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimStarterReward' : IDL.Func([], [], []),
  'enforceAdminCashLeadership' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCash' : IDL.Func([], [Cash], ['query']),
  'getCashLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getPlayerStatus' : IDL.Func([], [Player], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeCash' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'upgradeSpeed' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Cash = IDL.Nat;
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'cash' : IDL.Nat,
  });
  const PlayerID = IDL.Principal;
  const Time = IDL.Int;
  const Speed = IDL.Nat;
  const Player = IDL.Record({
    'id' : PlayerID,
    'cash' : Cash,
    'joinedAt' : Time,
    'hasClaimedReward' : IDL.Bool,
    'clickSpeed' : Speed,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCash' : IDL.Func([], [], []),
    'adminAddCash' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimStarterReward' : IDL.Func([], [], []),
    'enforceAdminCashLeadership' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCash' : IDL.Func([], [Cash], ['query']),
    'getCashLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPlayerStatus' : IDL.Func([], [Player], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeCash' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'upgradeSpeed' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };